server:
  port: 8080

spring:
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: drone_id
      auto-offset-reset: earliest

topic:
  name:
    consumer: fiap.scjr.agromonitor

  auto:
    create:
      topic:
        enabled: false
